package com.hgz.entity;

import java.io.Serializable;

public class TProductType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.pid
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_type.flag
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Boolean flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.id
     *
     * @return the value of t_product_type.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.id
     *
     * @param id the value for t_product_type.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.name
     *
     * @return the value of t_product_type.name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.name
     *
     * @param name the value for t_product_type.name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.pid
     *
     * @return the value of t_product_type.pid
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.pid
     *
     * @param pid the value for t_product_type.pid
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_type.flag
     *
     * @return the value of t_product_type.flag
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_type.flag
     *
     * @param flag the value for t_product_type.flag
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }
}