package com.hgz.entity;

import java.io.Serializable;
import java.util.Date;

public class TProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.price
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sale_price
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Long salePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.images
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.sale_point
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String salePoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.flag
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.create_time
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.update_time
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type_id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type_name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.price
     *
     * @return the value of t_product.price
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.price
     *
     * @param price the value for t_product.price
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sale_price
     *
     * @return the value of t_product.sale_price
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Long getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sale_price
     *
     * @param salePrice the value for t_product.sale_price
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setSalePrice(Long salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.images
     *
     * @return the value of t_product.images
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.images
     *
     * @param images the value for t_product.images
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.sale_point
     *
     * @return the value of t_product.sale_point
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getSalePoint() {
        return salePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.sale_point
     *
     * @param salePoint the value for t_product.sale_point
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setSalePoint(String salePoint) {
        this.salePoint = salePoint == null ? null : salePoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.flag
     *
     * @return the value of t_product.flag
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.flag
     *
     * @param flag the value for t_product.flag
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.create_time
     *
     * @return the value of t_product.create_time
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.create_time
     *
     * @param createTime the value for t_product.create_time
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.update_time
     *
     * @return the value of t_product.update_time
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.update_time
     *
     * @param updateTime the value for t_product.update_time
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type_id
     *
     * @return the value of t_product.type_id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type_id
     *
     * @param typeId the value for t_product.type_id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type_name
     *
     * @return the value of t_product.type_name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type_name
     *
     * @param typeName the value for t_product.type_name
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}