package com.hgz.entity;

import java.io.Serializable;

public class TProductDesc implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.product_id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_desc.product_desc
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.id
     *
     * @return the value of t_product_desc.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.id
     *
     * @param id the value for t_product_desc.id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.product_id
     *
     * @return the value of t_product_desc.product_id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.product_id
     *
     * @param productId the value for t_product_desc.product_id
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_desc.product_desc
     *
     * @return the value of t_product_desc.product_desc
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_desc.product_desc
     *
     * @param productDesc the value for t_product_desc.product_desc
     *
     * @mbg.generated Sun Mar 14 17:53:59 CST 2021
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }
}